
import LoginPage from '@/components/Login/LoginPage';
import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
  title: "U_M_LoginPage ",
  description: "Generated by Sumon Hasan",
};


const Login = () => {
  return (
   <LoginPage/>
  );
};

export default Login;